=== Roimartinezr/medousa/backend/whoare/adapters/schema/whois_response.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "WHOIS Response Model",
  "type": "object",
  "properties": {
    "tld": { "type": "string" },
    "registry": { "type": "string" },
    "country": { 
      "type": ["object", "null"],
      "properties": {
        "code": { "type": ["string", "null"] },
        "state": { 
            "type": ["string", "array", "null"],
            "items": { "type": "string" } 
        },
        "city": { "type": ["string", "null"] }
      }
    },
    "fields": {
      "type": "object",
      "properties": {
        "domain_name": { "type": ["string", "null"] },
        "registrant": { "type": ["string", "null"] },
        "registrant_name": { "type": ["string", "null"] },
        "registrar": { "type": ["string", "null"] },
        "emails" : { 
            "type": ["string", "array", "null"],
            "items": { "type": "string" } 
        },
        "creation_date": { "type": ["string", "null"] },
        "expiration_date": { "type": ["string", "null"] },
        "updated_date": { "type": ["string", "null"] },
        "name_servers": { 
            "type": ["string", "array", "null"],
            "items": { "type" : "string" } 
        },
        "status": {
          "type": ["string", "array", "null"],
          "items": { "type": "string" }
        }
      },
      "additionalProperties": true
    }
  },
  "required": ["tld", "fields"]
}

=== Roimartinezr/medousa/backend/whoare/adapters/io.json
{
  "tld": "io",
  "registry": "ICB",
  "country": {
    "code": "registrant_country",
    "state": "registrant_state_province",
    "city": null
  },
  "fields": {
    "domain_name": "domain_name",
    "registrant": "registrant_name",
    "registrant_name": null,
    "registrar": "registrar",
    "emails": null,
    "creation_date": {
      "source": "creation_date",
      "normalize": "first" 
    },
    "expiration_date": "registry_expiry_date",
    "updated_date": {
      "source": "updated_date",
      "normalize": "last" 
    },
    "name_servers": "name_servers",
    "status": "status"
  }
}

=== Roimartinezr/medousa/backend/whois/adapters/cx.json
{
  "tld": "cx",
  "registry": "cxDA",
  "country": {
    "code": "country_code",
    "state": "country_state",
    "city": "country_city"
  },
  "fields": {
    "domain_name": "domain_name",
    "registrant": "registrant",
    "registrant_name": "registrant_name", 
    "registrar": "registrar",
    "emails": null,
    "creation_date": "creation_date",
    "expiration_date": "expiration_date",
    "updated_date": "updated_date",
    "name_servers": "name_servers",
    "status": "status"
  }
}

=== Roimartinezr/medousa/backend/whoare/adapters/vg.json
{
  "tld": "vg",
  "registry": "Adamsnames",
  "country": {
    "code": "registrant_contact__country",
    "state": "registrant_contact__state",
    "city": null
  },
  "fields": {
    "domain_name": "domain_information__domain",
    "registrant": null,
    "registrant_name": null, 
    "registrar": "registrar_information__registrar",
    "emails": null,
    "creation_date": "domain_information__registered_on",
    "expiration_date": "domain_information__expires_on",
    "updated_date": "domain_information__updated_on",
    "name_servers": "domain_information__name_servers",
    "status": "domain_information__status"
  }
}

=== Roimartinezr/medousa/backend/whoare/adapters/ai.json
{
  "tld": "ai",
  "registry": "Vince Cate (OIS)",
  "country": {
    "code": "admin_country",
    "state": "admin_state",
    "city": "admin_city"
  },
  "fields": {
    "domain_name": "domain_name",
    "registrant": "registrant_org",
    "registrant_name": "registrant_name", 
    "registrar": "registrar",
    "emails": "registrant_email",
    "creation_date": "creation_date",
    "expiration_date": "expiration_date",
    "updated_date": "updated_date",
    "name_servers": "name_servers",
    "status": "status"
  }
}

=== Roimartinezr/medousa/backend/whoare/adapters/cc.json
{
  "tld": "cc",
  "registry": "VeriSign",
  "country": {
    "code": "country",
    "state": "state",
    "city": "city"
  },
  "fields": {
    "domain_name": "domain_name",
    "registrant": "org",
    "registrant_name": "name", 
    "registrar": "registrar",
    "emails": "emails",
    "creation_date": "creation_date",
    "expiration_date": "expiration_date",
    "updated_date": {
      "source": "updated_date",
      "normalize": "last" 
    },
    "name_servers": "name_servers",
    "status": "status"
  }
}
